FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y \
    chromium-driver \
    chromium

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "10000"]
